### ISSUE TITLE
We need a page that looks like the following

### ISSUE THREAD

**Issue by bb128b** [128BitStudios/saynototrackandtrace#2]
I have already started this but it is called the "login" page, this needs to be renamed to "checkin" and the following template design applied.

![IMG_5946](https://user-images.githubusercontent.com/2276905/95030548-790b7b00-06a8-11eb-8a19-1871e348e8e0.PNG)

**Comment by IMPrimph** [comment]
@bb128b 
I can do this using HTML and CSS

**Comment by bb128b** [comment]
@IMPrimph cool! Please make a PR

**Comment by bb128b** [comment]
@IMPrimph would you still like to do this one? I can assign you if so

**Comment by IMPrimph** [comment]
@bb128b 
Sorry, I have some urgent personal issue.
You can assign this to another dev

**Comment by bb128b** [comment]
I'm going to work on this now
